export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const LOAD_SHIFTS = 'LOAD_SHIFTS';
export const LOAD_SHIFTS_SUCCESS = 'LOAD_SHIFTS_SUCCESS';
export const LOAD_SHIFTS_ERROR = 'LOAD_SHIFTS_ERROR';

export const FILTER_EMPLOYEES = 'FILTER_EMPLOYEES';
